### ISSUE TITLE
Environment variable DISPLAY is hardcoded

### ISSUE THREAD

**Issue by qsorix** [jvenant/passff#99]
Hi. I've stumbled upon an issue when running passff in a system that uses [qingy](http://qingy.sourceforge.net/).

In my environment, proper value of `DISPLAY` is `:1.0`. Because in passff's code it is hardcoded to `:0.0`, gpg-agent cannot show the password prompt (i.e. run pinentry).

`DISPLAY` should be set to the same value as Firefox'es environment.

```js
  getEnvParams: function() {
    return [
      'HOME=' + PassFF.Preferences.home,
      'DISPLAY=:0.0',
      'TREE_CHARSET=ISO-8859-1',
      'GNUPGHOME=' + PassFF.Preferences.gnupgHome
    ];
  },
```

**Comment by sometoby** [comment]
I've pushed a fix for this problem. Would you mind checking out the current master, building the addon and testing if the fix worked?

**Comment by qsorix** [comment]
Hi. Thanks for a quick fix. I checked out master and installed it. However, I'm still getting that error 'passphrase to gpg-agent first'.

Either I did something wrong, or there is still something else broken, or the fix didn't work.

It would be great to have a page on project's wiki that explains how to build and install it, so I'm sure I did it right. If you document how to run firefox to get some logs or whatever can be helpful to diagnose it, i'll be happy to try that too. I guess I could read some tutorials on doing FF extensions, but right now I'm short on time, sorry.

**Comment by sometoby** [comment]
I suspect there might be something else wrong. What version of gpg-agent are you running?

**Comment by qsorix** [comment]
Hi, sorry for the delay. Here are the version numbers:
```bash
% gpg-agent --version
gpg-agent (GnuPG) 2.0.26
libgcrypt 1.5.4
Copyright (C) 2013 Free Software Foundation, Inc.
...
```

```bash
% gpg --version 
gpg (GnuPG) 2.0.26
libgcrypt 1.5.4
Copyright (C) 2013 Free Software Foundation, Inc.
...
```

**Comment by qsorix** [comment]
It must be because of the `DISPLAY`. I've changed settings to run this script below instead of pass, and now it works just fine. So either I've tested your fix in a wrong way, or there's sth wrong with that fix?

```bash
% cat ~/bin/pass
#!/bin/sh
DISPLAY=:1.0 exec /usr/bin/pass "$@"
```

**Comment by jvenant** [comment]
How do you execute pass from the plugin ? through shell ? or direct call ?
anyway could you try using the other way 
(for the through shell way, don't forget to add the --login argument to the shell)

**Comment by qsorix** [comment]
So I've checked both ways and neither passed DISPLAY in the environment. Then I finally had time to debug the fix by @sometoby. There's a bug caused by different than expected precedence of + and ?: operators.

After adding parentheses, it works just fine :)

```diff
     return [
       'HOME=' + PassFF.Preferences.home,
-      'DISPLAY=' + env.exists('DISPLAY') ? env.get('DISPLAY') : ':0.0',
+      'DISPLAY=' + (env.exists('DISPLAY') ? env.get('DISPLAY') : ':0.0'),
       'TREE_CHARSET=ISO-8859-1',
       'GNUPGHOME=' + PassFF.Preferences.gnupgHome
     ];
```

**Comment by jvenant** [comment]
That's right : ternary operator priority level can be a little bit tricky to manage. 
I applied your fix on the master.

Thank you very much for your contribution

**Comment by sometoby** [comment]
Huh, that one caught me off guard. Thanks for taking the initiative!
